### ISSUE TITLE
Associative array merge not working

### ISSUE THREAD

**Issue by omerts** [qualiancy/tea-merge#1]
Hello,

I am trying to merge two arrays, where the keys are strings. In such a case, the array's length is always 0, since length only counts numeric keys, and therefore the array merge loop isn't really looping over anything.

Omer

**Comment by logicalparadox** [comment]
That is generally considered a bad practice in JavaScript as it creates weird behavior. Internally it will store it as an object so you can work with it but when attempting to detect the type (`Array.isArray`) will still return true, which is why this library doesn't work. You should just use objects (`{}`) and then this library will work just fine.

Also, as a side note, I will depreciating this codebase in favor of  [vesln/params](https://github.com/vesln/params/blob/master/index.js#L65), for which I have donated this codebase to. I recommend you make the switch. The documentation needs updating, but its all there.

``` js
var merge = require('params').merge
```

**Comment by omerts** [comment]
@logicalparadox  Ended up using objects, and it works great. Thank you.
